spring.application.name=netflix-recommend

spring.ai.google.genai.api-key={$GEMINI_API}

spring.ai.google.genai.chat.options.model={$MODEL}
spring.ai.google.genai.embedding.text.model={$MODEL}
spring.ai.google.genai.embedding.api-key={$GEMINI_API}
