spring.application.name=multomodal
spring.ai.google.genai.api-key={KEY}

spring.ai.google.genai.chat.model={MODEL}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

