spring.application.name=taskClient
server.port=8080
spring.ai.google.genai.api-key={KEY}
spring.ai.mcp.client.streamable-http.connections.task-server.url=http://localhost:8081
spring.ai.google.genai.chat.model={MODEL}