spring.application.name=rag
spring.ai.google.genai.api-key={}

spring.ai.google.genai.chat.options.model={}
spring.ai.google.genai.embedding.text.model={}
spring.ai.google.genai.embedding.api-key={}

spring.ai.vectorstore.pinecone.api-key={}
spring.ai.vectorstore.pinecone.index-name={}
spring.ai.vectorstore.pinecone.namespace={}
spring.ai.google.genai.embedding.text.dimensions={}

